version: "3.4"
services:
  vite_docker:
    image: node:18-alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8080:8080
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
